// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0gkcKRMlr_Et4QDaOnOZUItNrqdZMt8',
    appId: '1:475502433301:web:d1f60a9ffa7c808f2eea1c',
    messagingSenderId: '475502433301',
    projectId: 'reel-organizer',
    authDomain: 'reel-organizer.firebaseapp.com',
    storageBucket: 'reel-organizer.firebasestorage.app',
    measurementId: 'G-1C1QNHDW56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpUaywUcctK0BQ2ulJeynvCDrUY19n5dg',
    appId: '1:475502433301:android:c5ba542712f4eaca2eea1c',
    messagingSenderId: '475502433301',
    projectId: 'reel-organizer',
    storageBucket: 'reel-organizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD05CHrnQNXc4tkLnii3sFR5A8IQ46WgG8',
    appId: '1:475502433301:ios:b710b4fc616237662eea1c',
    messagingSenderId: '475502433301',
    projectId: 'reel-organizer',
    storageBucket: 'reel-organizer.firebasestorage.app',
    iosBundleId: 'com.example.reelOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD05CHrnQNXc4tkLnii3sFR5A8IQ46WgG8',
    appId: '1:475502433301:ios:b710b4fc616237662eea1c',
    messagingSenderId: '475502433301',
    projectId: 'reel-organizer',
    storageBucket: 'reel-organizer.firebasestorage.app',
    iosBundleId: 'com.example.reelOrganizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl0gkcKRMlr_Et4QDaOnOZUItNrqdZMt8',
    appId: '1:475502433301:web:3d49f971f6dc8a772eea1c',
    messagingSenderId: '475502433301',
    projectId: 'reel-organizer',
    authDomain: 'reel-organizer.firebaseapp.com',
    storageBucket: 'reel-organizer.firebasestorage.app',
    measurementId: 'G-0G0HP7S1HS',
  );
}
